### ISSUE TITLE
getFormData index out of range

### ISSUE THREAD

**Issue by Malspherus** [garzj/digi4school#1]
Hi, I tried downloading one of the currently free books (https://a.digi4school.at/ebook/5495/) but got this error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 129, in main
  File "<input>", line 73, in downloadBook
  File "<input>", line 39, in getFormData
IndexError: list index out of range
```

I started downloading from page 1

**Comment by garzj** [comment]
Should be fixed now!

But look at the README again, I changed a lot.
